"""empty message

Revision ID: 68057f23d634
Revises: d12482ac5e99
Create Date: 2022-06-01 18:10:33.561067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68057f23d634'
down_revision = 'd12482ac5e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_token', table_name='user')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'token')
    op.drop_column('user', 'token_exp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_exp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_user_token', 'user', ['token'], unique=False)
    # ### end Alembic commands ###
