"""empty message

Revision ID: 6cb01527cdb1
Revises: 481b0e81ea63
Create Date: 2022-05-17 17:59:47.112908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb01527cdb1'
down_revision = '481b0e81ea63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
